### ISSUE TITLE
error: Uncaught TypeError: Cannot call method 'insertBefore' of null 

### ISSUE THREAD

**Issue by puckey** [component/has-translate3d#1]
This is throwing the following error, when I use it in component/swipe:
Uncaught TypeError: Cannot call method 'insertBefore' of null 

which is referring to the following line:

```
document.body.insertBefore(el, null);
```

**Comment by rauchg** [comment]
What browser is this ?

**Comment by puckey** [comment]
Latest chrome.. But of course now I see that it was because I was calling it before the dom had loaded..
