### ISSUE TITLE
Object doesn't support property or method 'getComputedStyle'.

### ISSUE THREAD

**Issue by yields** [component/has-translate3d#3]
this is the IE8 error message that freezes my app lol.
https://github.com/component/has-translate3d/blob/master/index.js#L17
## Edit

i should say that i get this error when in IE9 in IE8 mode, it's weird since
https://github.com/component/has-translate3d/blob/master/index.js#L17
IE8 doesn't have transform property.

**Comment by rauchg** [comment]
What's the error message?

**Comment by rauchg** [comment]
Oh I see it's in the issue title.
